version: 2
jobs:
  test:
    docker:
      - image: "node:6.11.1"
    steps:
      - checkout
      - restore_cache:
          key: v3-excella-central-npm-{{ checksum "package-lock.json" }}
      - run: yarn global add npm@5
      - run: npm install --unsafe-perm
      - save_cache:
          key: v3-excella-central-npm-{{ checksum "package-lock.json" }}
          paths:
            - "~/.npm"
            - "node_modules"
      - run: npm run check

  build_android:
    docker:
      - image: bitriseio/docker-android
    steps:
      - checkout
      - restore_cache:
          key: v3-excella-central-android-{{ checksum "package-lock.json" }}
      - run: npm install --unsafe-perm
      - run: npm run android:build
      - save_cache:
          key: v3-excella-central-android-{{ checksum "package-lock.json" }}
          paths:
            - "~/.npm"
            - "~/.android"
            - "node_modules"
      - store_artifacts:
          path: android/artifacts/app-release.apk
          destination: release.apk

  build_ios:
    machine: true
    environment:
      NODE_VERSION: 6.11.1
    steps:
      - checkout
      - restore_cache:
          key: v3-excella-central-ios-{{ checksum "package-lock.json" }}-{{ checksum "_cordova/package-lock.json" }}
      - run: bash scripts/setupiOS.sh
      - run: npm install --unsafe-perm --no-save
      - run: npm run cordova:prepare
      - run: git checkout -- _cordova/package-lock.json
      - save_cache:
          key: v3-excella-central-ios-{{ checksum "package-lock.json" }}-{{ checksum "_cordova/package-lock.json" }}
          paths:
            - "~/.npm"
            - "node_modules"
            - "_cordova/node_modules"
            - "_cordova/plugins"
            - "_cordova/platforms"
      - run: npm run www
      - run: bash scripts/buildiOS.sh
      - store_artifacts:
          path: _cordova/builds/local/Excella-Central.ipa
          destination: local.ipa
      - store_artifacts:
          path: _cordova/builds/debug/Excella-Central.ipa
          destination: debug.ipa
      - store_artifacts:
          path: _cordova/builds/release/Excella-Central.ipa
          destination: release.ipa

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_android:
          filters:
            branches:
              only: master
      #- build_ios:
      #    filters:
      #      branches:
      #        only: master